/**
 * Sidebars configuration for Physical AI Textbook
 * Separate sidebars for English and Urdu documentation
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Sidebar for English docs
  englishSidebar: [
    {
      type: 'autogenerated',
      dirName: 'en', // Only scan web/docs/en
    },
  ],
  // Sidebar for Urdu docs
  urduSidebar: [
    {
      type: 'autogenerated',
      dirName: 'ur', // Only scan web/docs/ur
    },
  ],
};

module.exports = sidebars;
